
name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]


env:
    BUILD_TYPE: Release
  
jobs:
  build-ubuntu:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: upgrade
      run: sudo apt update; sudo apt install -y tzdata gcc g++ clang cmake
    - name: install qt
      run: sudo apt install -y qt5-default qtbase5-dev qttools5-dev  qtbase5-dev-tools qtcreator libqt5charts5-dev qtwebengine5-dev doxygen doxygen-latex doxygen2man
    - name: configure
      run: mkdir build && cd build && cmake -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} ..
    - name: build
      run: cmake --build build
